apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  annotations:
    field.cattle.io/creatorId: user-tc7xc
  creationTimestamp: '2023-03-28T02:30:47Z'
  finalizers:
    - wrangler.cattle.io/provisioning-cluster-remove
    - wrangler.cattle.io/rke-cluster-remove
    - wrangler.cattle.io/cloud-config-secret-remover
  generation: 3
  managedFields:
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            v:"wrangler.cattle.io/cloud-config-secret-remover": {}
      manager: rancher-v2.6.11-secret-migrator
      operation: Update
      time: '2023-03-28T02:30:48Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:agentDeployed: {}
          f:clientSecretName: {}
          f:clusterName: {}
          f:conditions: {}
          f:observedGeneration: {}
          f:ready: {}
      manager: rancher
      operation: Update
      subresource: status
      time: '2023-03-28T02:38:50Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/provisioning-cluster-remove": {}
            v:"wrangler.cattle.io/rke-cluster-remove": {}
        f:spec:
          .: {}
          f:cloudCredentialSecretName: {}
          f:defaultPodSecurityPolicyTemplateName: {}
          f:kubernetesVersion: {}
          f:localClusterAuthEndpoint:
            .: {}
            f:caCerts: {}
            f:enabled: {}
            f:fqdn: {}
          f:rkeConfig:
            .: {}
            f:additionalManifest: {}
            f:chartValues:
              .: {}
              f:harvester-cloud-provider:
                .: {}
                f:cloudConfigPath: {}
                f:clusterName: {}
              f:rke2-calico: {}
            f:etcd:
              .: {}
              f:disableSnapshots: {}
              f:snapshotRetention: {}
              f:snapshotScheduleCron: {}
            f:machineGlobalConfig:
              .: {}
              f:cni: {}
              f:disable-kube-proxy: {}
              f:etcd-expose-metrics: {}
              f:profile: {}
            f:machinePools: {}
            f:machineSelectorConfig: {}
            f:registries:
              .: {}
              f:configs: {}
              f:mirrors: {}
            f:upgradeStrategy:
              .: {}
              f:controlPlaneConcurrency: {}
              f:controlPlaneDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
              f:workerConcurrency: {}
              f:workerDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
      manager: rancher
      operation: Update
      time: '2023-03-28T02:57:19Z'
  name: haus11
  namespace: fleet-default
  resourceVersion: '2188938'
  uid: 15de3767-65f9-47ce-b996-ccee16d3fba4
spec:
  cloudCredentialSecretName: cattle-global-data:cc-rqhq8
  defaultPodSecurityPolicyTemplateName: ''
  kubernetesVersion: v1.24.10+rke2r1
  localClusterAuthEndpoint:
    caCerts: ''
    enabled: false
    fqdn: ''
  rkeConfig:
    additionalManifest: |
      ---
      apiVersion: helm.cattle.io/v1
      kind: HelmChartConfig
      metadata:
        name: rke2-ingress-nginx
        namespace: kube-system
      spec:
        valuesContent: |-
          controller:
            extraArgs:
              enable-ssl-passthrough: true
    chartValues:
      harvester-cloud-provider:
        cloudConfigPath: /var/lib/rancher/rke2/etc/config-files/cloud-provider-config
        clusterName: haus11
      rke2-calico: {}
    etcd:
      disableSnapshots: false
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: false
      etcd-expose-metrics: false
      profile: null
    machinePools:
      - controlPlaneRole: true
        etcdRole: true
        machineConfigRef:
          kind: HarvesterConfig
          name: nc-haus11-pool1-8lztw
        name: pool1
        quantity: 3
        unhealthyNodeTimeout: 0s
        workerRole: true
    machineSelectorConfig:
      - config:
          cloud-provider-config: secret://fleet-default:harvesterconfigrb9m5
          cloud-provider-name: harvester
          protect-kernel-defaults: false
    registries:
      configs: {}
      mirrors: {}
    upgradeStrategy:
      controlPlaneConcurrency: '1'
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: '1'
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
status:
  agentDeployed: true
  clientSecretName: haus11-kubeconfig
  clusterName: c-m-s6ct4jm7
  conditions:
    - lastUpdateTime: '2023-03-28T02:38:50Z'
      status: 'False'
      type: Reconciling
    - lastUpdateTime: '2023-03-28T02:30:47Z'
      status: 'False'
      type: Stalled
    - lastUpdateTime: '2023-04-10T03:20:33Z'
      status: 'True'
      type: Created
    - lastUpdateTime: '2023-04-22T19:01:33Z'
      status: 'True'
      type: RKECluster
    - lastUpdateTime: '2023-03-28T02:30:48Z'
      status: 'True'
      type: HarvesterCloudProviderConfigMigrated
    - lastUpdateTime: '2023-03-28T02:30:47Z'
      status: 'True'
      type: BackingNamespaceCreated
    - lastUpdateTime: '2023-03-28T02:30:47Z'
      status: 'True'
      type: DefaultProjectCreated
    - lastUpdateTime: '2023-03-28T02:30:48Z'
      status: 'True'
      type: SystemProjectCreated
    - lastUpdateTime: '2023-03-28T02:30:48Z'
      status: 'True'
      type: InitialRolesPopulated
    - lastUpdateTime: '2023-03-28T02:30:49Z'
      status: 'True'
      type: CreatorMadeOwner
    - lastUpdateTime: '2023-03-28T02:32:11Z'
      status: 'True'
      type: Provisioned
    - lastUpdateTime: '2023-03-28T02:30:51Z'
      status: 'True'
      type: NoDiskPressure
    - lastUpdateTime: '2023-03-28T02:30:51Z'
      status: 'True'
      type: NoMemoryPressure
    - lastUpdateTime: '2023-03-28T02:30:52Z'
      status: 'True'
      type: SecretsMigrated
    - lastUpdateTime: '2023-03-28T02:30:52Z'
      status: 'True'
      type: ServiceAccountSecretsMigrated
    - lastUpdateTime: '2023-03-28T02:30:52Z'
      status: 'True'
      type: RKESecretsMigrated
    - lastUpdateTime: '2023-04-10T03:20:32Z'
      status: 'False'
      type: Connected
    - lastUpdateTime: '2023-04-22T19:01:33Z'
      message: >-
        configuring bootstrap node(s) haus11-pool1-647f8f9bd7-4tjrk: waiting for
        probes: calico, etcd, kube-apiserver, kube-controller-manager
      reason: Waiting
      status: Unknown
      type: Updated
    - lastUpdateTime: '2023-04-10T03:20:32Z'
      message: Cluster agent is not connected
      reason: Disconnected
      status: 'False'
      type: Ready
    - lastUpdateTime: '2023-03-28T02:38:20Z'
      status: 'True'
      type: GlobalAdminsSynced
    - lastUpdateTime: '2023-03-28T02:38:22Z'
      status: 'True'
      type: SystemAccountCreated
    - lastUpdateTime: '2023-03-28T02:38:28Z'
      status: 'True'
      type: AgentDeployed
    - lastUpdateTime: '2023-03-28T02:38:50Z'
      status: 'True'
      type: Waiting
  observedGeneration: 3
  ready: true
