apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-daemonset-loadbalancer
  namespace: kube-system
  annotations:
    cloudprovider.harvesterhci.io/ipam: pool
spec:
  selector:
    app.kubernetes.io/name: rke2-ingress-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
  type: LoadBalancer